Cumulative commits which were released with blueCFD-Core 2.3-1. For release notes, check the page http://bluecfd.github.io/Core/ReleaseNotes/
This commit includes all of the patches, modifications and additions needed for making OpenFOAM build and work on Windows Operating Systems.
It includes changes made by Symscape and FSD blueCAPE, where each one of the modified files should disclaim who made which changes.
A full git development tree is not provided, due to incorrect user-email signing.

If you find any changes that have been made and not properly assigned to their original authors, please report at https://github.com/blueCFD/Core/issues

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,5 +1,6 @@
 #!/bin/sh
 cd ${0%/*} || exit 1    # run from this directory
+allwmakeOptions='-allow-doc doDoxygen' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
 
 wmakeCheckPwd "$WM_PROJECT_DIR" || {
     echo "Error: Current directory is not \$WM_PROJECT_DIR"
@@ -15,7 +16,39 @@ wmakeCheckPwd "$WM_PROJECT_DIR" || {
 }
 
 # wmake is required for subsequent targets
-( cd wmake/src && make )
+if ! isMinGW; then
+
+  ( cd wmake/src && make )
+
+elif ! onWin; then
+
+  if [ -d "wmake/bin/$WM_ARCH$WM_COMPILER" ]; then
+    filecount=`ls -1A "wmake/bin/$WM_ARCH$WM_COMPILER" | wc -l`
+  fi
+
+  if [ "$filecount" = "0" -o ! -d "wmake/platforms/$WM_ARCH$WM_COMPILER" ]; then
+    ( cd wmake/src && make WMAKE_BIN="${WM_DIR}/platforms/${WM_ARCH}${WM_COMPILER}_win" EXE_EXTENSION=".exe" ADDITIONAL_CFLAGS="_WIN_HACK_" )
+    ( cd wmake/src && make cc="gcc" CC="g++" )
+  fi
+  filecount=`ls -1A "wmake/platforms/$WM_ARCH$WM_COMPILER" | wc -l`
+
+  #use the wmake compiled for linux usage, if not built with system's gcc
+  if [ "$filecount" = "0" -o ! -d "wmake/platforms/$WM_ARCH$WM_COMPILER" ]; then
+    echo "Aborting Allwmake, because a working wmake wasn't found nor built."
+    exit 1
+  fi
+  unset filecount
+
+else
+
+  (
+    cd wmake/src && \
+    make && \
+    mv ${WM_DIR}/platforms/${WM_ARCH}${WM_COMPILER}/wmkdepend.exe \
+       ${WM_DIR}/platforms/${WM_ARCH}${WM_COMPILER}/wmkdep.exe
+  )
+
+fi
 
 # build ThirdParty sources
 if [ -d "$WM_THIRD_PARTY_DIR" ]
@@ -29,7 +62,7 @@ fi
 src/Allwmake $*
 applications/Allwmake $*
 
-if [ "$1" = doc ]
+if [ $doDoxygen -gt 0 ]
 then
     doc/Allwmake $*
 fi
diff --git a/wmake/scripts/makeDerivedFiles b/wmake/scripts/makeDerivedFiles
--- a/wmake/scripts/makeDerivedFiles
+++ b/wmake/scripts/makeDerivedFiles
@@ -6,8 +6,10 @@
 #   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
+# 2014-02-21 blueCAPE Lda: Modifications for blueCFD-Core 2.3
+#------------------------------------------------------------------------------
 # License
-#     This file is part of OpenFOAM.
+#     This file is a derivative work of OpenFOAM.
 #
 #     OpenFOAM is free software: you can redistribute it and/or modify it
 #     under the terms of the GNU General Public License as published by
@@ -22,6 +24,19 @@
 #     You should have received a copy of the GNU General Public License
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
 #
+# Modifications
+#     This file has been modified by blueCAPE's unofficial mingw patches for
+#     OpenFOAM.
+#     For more information about these patches, visit:
+#         http://bluecfd.com/Core
+#
+#     Modifications made:
+#        - Derived from the patches for blueCFD 2.1 and 2.2.
+#        - Added the ability to build localized builds for each MPI toolbox.
+#        - Added ability to build the resource files for embedding into the
+#          binaries, therefore allowing us to add version information to the
+#          binaries for Windows to see.
+#
 # Script
 #     makeDerivedFiles
 #
@@ -31,16 +46,55 @@
 #
 #------------------------------------------------------------------------------
 
-[ -d "$WM_OPTIONS" ] || {
-    echo "The '$WM_OPTIONS' directory does not exist, exiting" 1>&2
+[ -z "$WM_OPTIONS_LOCAL" ] && WM_OPTIONS_LOCAL=$WM_OPTIONS
+
+[ -d "$WM_OPTIONS_LOCAL" ] || {
+    echo "The '$WM_OPTIONS_LOCAL' directory does not exist, exiting" 1>&2
     exit 1
 }
 
 # change to the $WM_OPTIONS directory
-cd "$WM_OPTIONS" 2>/dev/null || {
-    echo "Could not change to directory '$WM_OPTIONS'" 1>&2
+cd "$WM_OPTIONS_LOCAL" 2>/dev/null || {
+    echo "Could not change to directory '$WM_OPTIONS_LOCAL'" 1>&2
     exit 1
 }
+
+# special preparations for MinGW builds
+TIS_MinGW=0
+if isMinGW && [ "$makeOption" != "libo" -a "$makeOption" != "lib" ]; then
+    if [ -e "$FOAM_SRC/OSspecific/$WM_OSTYPE/res/OFversion_template.rc" ]; then
+        TIS_MinGW=1
+        cp "$FOAM_SRC/OSspecific/$WM_OSTYPE/res/OFversion_template.rc" tmpver.rc
+    fi
+fi
+
+if [ $TIS_MinGW -eq 1 ]; then
+    #Extract the binary name
+    MGW_EXENAME=`grep -e "^EXE =" files`
+    MGW_LIBNAME=`grep -e "^LIB =" files`
+    MGW_FINALNAME="NONAME"
+
+    if [ -n "$MGW_EXENAME" ]; then
+        MGW_FINALNAME=`echo $MGW_EXENAME | sed -e 's=.*/=='`.exe
+    fi
+
+    if [ -n "$MGW_LIBNAME" ]; then
+        MGW_FINALNAME=`echo $MGW_LIBNAME | sed -e 's=.*/=='`.dll
+    fi
+
+    #get current OpenFOAM version
+    MGW_OFversion=`wmakePrintBuild -update`
+
+    #apply values to template
+    sed -e 's=2\.0\.\0\.0='$MGW_OFversion'=g' \
+        -e 's=tmpintname='$MGW_FINALNAME'=' \
+        -e 's=tmporigname='$MGW_FINALNAME'=' \
+        tmpver.rc > version_of_build.rc
+
+    #clean up
+    unset MGW_OFversion MGW_EXENAME MGW_LIBNAME MGW_FINALNAME
+    rm tmpver.rc
+fi
 
 # Find and keep macro definitions in files list
 grep "=" files > filesMacros
@@ -51,6 +105,11 @@ grep -v "=" files > filesPlusBlank
 # Add a newline to files to ensure the last line is followed by a newline
 echo "" >> filesPlusBlank
 
+# Plug in the version resource file for being compiled along
+if [ $TIS_MinGW -eq 1 ]; then
+    echo "Make/$WM_OPTIONS_LOCAL/version_of_build.rc" >> filesPlusBlank
+    echo "" >> filesPlusBlank
+fi
 
 # Remove commented lines, blank lines, and trailing blanks from files
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
